# Generated by Django 5.2.6 on 2025-09-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.TextField(blank=True, null=True, verbose_name="用户名"),
                ),
                (
                    "fansCount",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="粉丝数量"
                    ),
                ),
                (
                    "describe",
                    models.TextField(blank=True, null=True, verbose_name="视频描述"),
                ),
                (
                    "videoId",
                    models.TextField(blank=True, null=True, verbose_name="视频id"),
                ),
                (
                    "createTime",
                    models.TextField(blank=True, null=True, verbose_name="发表时间"),
                ),
                (
                    "videoTime",
                    models.TextField(blank=True, null=True, verbose_name="视频时长"),
                ),
                (
                    "likeCount",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="点赞数量"
                    ),
                ),
                (
                    "collectCount",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="收藏数量"
                    ),
                ),
                (
                    "commentCount",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="评论数量"
                    ),
                ),
                (
                    "downloadCount",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="下载数量"
                    ),
                ),
                (
                    "shareCount",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="分享数量"
                    ),
                ),
            ],
            options={
                "verbose_name": "视频数据",
                "db_table": "video_data",
            },
        ),
    ]
