# Generated by Django 5.2.6 on 2025-09-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.TextField(blank=True, null=True, verbose_name="用户id"),
                ),
                (
                    "user_name",
                    models.TextField(blank=True, null=True, verbose_name="用户名"),
                ),
                (
                    "comment_time",
                    models.TextField(blank=True, null=True, verbose_name="评论时间"),
                ),
                (
                    "ip_address",
                    models.TextField(blank=True, null=True, verbose_name="IP地址"),
                ),
                (
                    "comment_content",
                    models.TextField(blank=True, null=True, verbose_name="评论内容"),
                ),
                (
                    "like_count",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="点赞数量"
                    ),
                ),
                (
                    "video_id",
                    models.TextField(blank=True, null=True, verbose_name="视频id"),
                ),
            ],
            options={
                "verbose_name": "评论信息",
                "db_table": "video_comment",
            },
        ),
        migrations.AlterModelOptions(
            name="videodata",
            options={"verbose_name": "视频信息"},
        ),
    ]
